<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <PlatformTarget>AnyCPU</PlatformTarget>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="resources\odc-sftp.png" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="resources\odc-sftp.png" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="OutSystems.ExternalLibraries.SDK" Version="1.4.0" />
        <PackageReference Include="SSH.NET" Version="2024.1.0" />
    </ItemGroup>
</Project>
